#pages:
#  stage: deploy
#  script:
#    - ls -la
#    - ls -la public
#  artifacts:
#    paths:
#      - public
#  only:
#    - master

pages:
  image: node:12.18
  stage: deploy
  before_script:
    - ls -la
  script:
    - npm install
    - npm run prod-build
    - ls -la
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
